CREATE USER muslib WITH ENCRYPTED PASSWORD 'password';

CREATE DATABASE muslib OWNER 'muslib';


-- GRANT ALL PRIVILEGES ON DATABASE muslib TO muslib;
-- GRANT ALL ON DATABASE muslib TO muslib;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO muslib;
